version: "3"

services:
  api:
    build: .
    container_name: speeches
    command: bin/setup
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    env_file: .env.development
    depends_on:
      - db
      - cache

  jobs:
    build: .
    container_name: sidekiq
    command: "bin/setup_sidekiq"
    volumes:
      - .:/opt/app
    env_file: .env.development
    depends_on:
      - db
      - cache

  db:
    image: postgres:13-alpine
    container_name: postgresql
    env_file: .env.database

  cache:
    image: redis
    container_name: redis
    volumes:
      - ./redis:/data
    command: "redis-server redis.conf"

  queue:
    image: redis
    container_name: queue_sidekiq
    command: "redis-server"

networks:
  platform_web_network:
    external: true
