default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: speeches_development

test:
  <<: *default
  database: speeches_test

production:
  <<: *default
  database: speeches_production
  username: speeches_tech
  password: <%= ENV['SPEECHES_DATABASE_PASSWORD'] %>
